params:
  model: RandomForestClassifier # LogisticRegression, LogisticRegressionCV RandomForestClassifier DecisionTreeClassifier
  model_args:
    n_estimators: 100
    max_depth:
    random_state: 42
    n_jobs: -1
